In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.Series([1, 2, 3, 4])

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
pd.Series([1, 2, 3, 4]).tolist()

[1, 2, 3, 4]

In [5]:
a = pd.Series([1, 2, 3, 4])
b = pd.Series([2, 4, 6, 8])
a+b

0     3
1     6
2     9
3    12
dtype: int64

In [6]:
a-b

0   -1
1   -2
2   -3
3   -4
dtype: int64

In [7]:
a*b

0     2
1     8
2    18
3    32
dtype: int64

In [8]:
a/b

0    0.5
1    0.5
2    0.5
3    0.5
dtype: float64

In [9]:
a > b

0    False
1    False
2    False
3    False
dtype: bool

In [11]:
a < b

0    True
1    True
2    True
3    True
dtype: bool

In [12]:
a == b

0    False
1    False
2    False
3    False
dtype: bool

In [13]:
pd.Series({'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800})

a    100
b    200
c    300
d    400
e    800
dtype: int64

In [14]:
pd.Series(np.array((2, 4, 6, 8)))

0    2
1    4
2    6
3    8
dtype: int32

In [18]:
a = pd.Series(('100', '200', 'python', '300'))
pd.to_numeric(a, errors='coerce')

0    100.0
1    200.0
2      NaN
3    300.0
dtype: float64

In [21]:
np.array(a)

array(['100', '200', 'python', '300'], dtype=object)

In [24]:
pd.Series((8, 2, 6, 1)).sort_values()

3    1
1    2
2    6
0    8
dtype: int64

In [25]:
pd.Series((8, 2, 6, 1)).append(pd.Series((3, 4)))

0    8
1    2
2    6
3    1
0    3
1    4
dtype: int64

In [26]:
a = pd.Series(np.arange(10))
a[a < 6]

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int32

In [31]:
a = pd.Series((1, 2, 3, 4), index=('A', 'B', 'C', 'D'))
a.reindex(('B', 'D', 'A', 'C'))

B    2
D    4
A    1
C    3
dtype: int64

In [32]:
a = pd.Series(np.arange(10))
a.mean()

4.5

In [33]:
a.std()

3.0276503540974917

In [36]:
a = pd.Series(np.arange(1, 6))
b = pd.Series(np.arange(2, 11, 2))

a[~a.isin(b)]

0    1
2    3
4    5
dtype: int32

In [37]:
a[a.isin(b)]

1    2
3    4
dtype: int32

In [39]:
np.union1d(a, b)

array([ 1,  2,  3,  4,  5,  6,  8, 10])

In [40]:
np.intersect1d(a, b)

array([2, 4])

In [42]:
a = pd.Series(np.random.random(20))
a.describe()

count    20.000000
mean      0.541072
std       0.320744
min       0.045150
25%       0.273224
50%       0.618153
75%       0.832185
max       0.940928
dtype: float64

In [51]:
pd.Series(np.random.randint(1, 11, 20)).value_counts()

7     4
4     3
8     3
1     2
3     2
5     2
6     2
10    2
dtype: int64

In [57]:
pd.Series(np.random.randint(1, 11, 20)).value_counts().values

array([4, 4, 2, 2, 2, 2, 2, 1, 1], dtype=int64)

In [58]:
np.where(pd.Series(np.random.randint(1, 11, 20)) % 5 == 0)

(array([ 4, 10, 14, 16], dtype=int64),)

In [59]:
a = pd.Series(np.random.randint(1, 11, 20))
a.take((1, 4, 5, 7))

1    7
4    5
5    4
7    3
dtype: int32

In [62]:
a = pd.Series(['php', 'python', 'java', 'c#'])
a.map(
    lambda _ : _[0].upper() + _[1:-1:] + _[-1].upper()
)

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

In [63]:
a.map(len)

0    3
1    6
2    4
3    2
dtype: int64

In [64]:
a = pd.Series(['01 Jan 2015',
               '10-02-2016',
               '20180307',
               '2014/05/06',
               '2016-04-12',
               '2019-04-06T11:20'])
pd.to_datetime(a)

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

In [65]:
pd.Series(pd.date_range('2020-01-01', periods=52, freq='W-SUN'))

0    2020-01-05
1    2020-01-12
2    2020-01-19
3    2020-01-26
4    2020-02-02
5    2020-02-09
6    2020-02-16
7    2020-02-23
8    2020-03-01
9    2020-03-08
10   2020-03-15
11   2020-03-22
12   2020-03-29
13   2020-04-05
14   2020-04-12
15   2020-04-19
16   2020-04-26
17   2020-05-03
18   2020-05-10
19   2020-05-17
20   2020-05-24
21   2020-05-31
22   2020-06-07
23   2020-06-14
24   2020-06-21
25   2020-06-28
26   2020-07-05
27   2020-07-12
28   2020-07-19
29   2020-07-26
30   2020-08-02
31   2020-08-09
32   2020-08-16
33   2020-08-23
34   2020-08-30
35   2020-09-06
36   2020-09-13
37   2020-09-20
38   2020-09-27
39   2020-10-04
40   2020-10-11
41   2020-10-18
42   2020-10-25
43   2020-11-01
44   2020-11-08
45   2020-11-15
46   2020-11-22
47   2020-11-29
48   2020-12-06
49   2020-12-13
50   2020-12-20
51   2020-12-27
dtype: datetime64[ns]

In [66]:
pd.DataFrame( {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})

X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

In [74]:
a = {
'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
b = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(a, index=b)
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [78]:
df.iloc[:3]

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

In [79]:
df[["name", "score"]]

name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

In [80]:
df.iloc[[1, 3, 5, 6], [1, 3]]

score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes

In [82]:
df[df["attempts"] > 2]

name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [83]:
df.shape

(10, 4)

In [88]:
df[df.isna().any(axis=1)]

name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

In [89]:
df[df["score"].between(15, 20)]

name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

In [90]:
df[ (df["attempts"] < 2) & (df["score"] > 15)]

name  score  attempts qualify
j  Jonas   19.0         1     yes

In [94]:
df.loc['d', 'score'] = 11.5
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [96]:
df["attempts"].sum()

19

In [98]:
df["score"].mean()

13.333333333333334

In [100]:
df.loc['k'] = ['Suresh', 15.5, 1, 'yes']
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

In [102]:
df.sort_values('name', ascending=False)

name  score  attempts qualify
k     Suresh   15.5         1     yes
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

In [103]:
df.sort_values('score')

name  score  attempts qualify
i      Kevin    8.0         2      no
b       Dima    9.0         3      no
e      Emily    9.0         2      no
d      James   11.5         3      no
a  Anastasia   12.5         1     yes
g    Matthew   14.5         1     yes
k     Suresh   15.5         1     yes
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
f    Michael   20.0         3     yes
h      Laura    NaN         1      no

In [106]:
df['qualify'].map({'yes': True, 'no': False})

a     True
b    False
c     True
d    False
e    False
f     True
g     True
h    False
i    False
j     True
k     True
Name: qualify, dtype: bool

In [110]:
df.pop('attempts')

a    1
b    3
c    2
d    3
e    2
f    3
g    1
h    1
i    2
j    1
k    1
Name: attempts, dtype: int64

In [111]:
df

name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James   11.5      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes
k     Suresh   15.5     yes

In [114]:
color = ['Red','Blue','Orange','Red','White','White','Blue','Green','Green','Red','Yellow']
df['color'] = color
df

name  score qualify   color
a  Anastasia   12.5     yes     Red
b       Dima    9.0      no    Blue
c  Katherine   16.5     yes  Orange
d      James   11.5      no     Red
e      Emily    9.0      no   White
f    Michael   20.0     yes   White
g    Matthew   14.5     yes    Blue
h      Laura    NaN      no   Green
i      Kevin    8.0      no   Green
j      Jonas   19.0     yes     Red
k     Suresh   15.5     yes  Yellow

In [121]:
for _ in df.iterrows():
    print(_)

('a', name       Anastasia
score           12.5
qualify          yes
color            Red
Name: a, dtype: object)
('b', name       Dima
score       9.0
qualify      no
color      Blue
Name: b, dtype: object)
('c', name       Katherine
score           16.5
qualify          yes
color         Orange
Name: c, dtype: object)
('d', name       James
score       11.5
qualify       no
color        Red
Name: d, dtype: object)
('e', name       Emily
score        9.0
qualify       no
color      White
Name: e, dtype: object)
('f', name       Michael
score         20.0
qualify        yes
color        White
Name: f, dtype: object)
('g', name       Matthew
score         14.5
qualify        yes
color         Blue
Name: g, dtype: object)
('h', name       Laura
score        NaN
qualify       no
color      Green
Name: h, dtype: object)
('i', name       Kevin
score        8.0
qualify       no
color      Green
Name: i, dtype: object)
('j', name       Jonas
score       19.0
qualify      yes
color        Red


In [123]:
df.columns.to_list()

['name', 'score', 'qualify', 'color']

In [124]:
df.columns.values

array(['name', 'score', 'qualify', 'color'], dtype=object)

In [125]:
# df.to_csv("test.csv")

In [126]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [127]:
df.fillna(0)

name  score qualify   color
a  Anastasia   12.5     yes     Red
b       Dima    9.0      no    Blue
c  Katherine   16.5     yes  Orange
d      James   11.5      no     Red
e      Emily    9.0      no   White
f    Michael   20.0     yes   White
g    Matthew   14.5     yes    Blue
h      Laura    0.0      no   Green
i      Kevin    8.0      no   Green
j      Jonas   19.0     yes     Red
k     Suresh   15.5     yes  Yellow

In [129]:
df['index'] = df.index
df

name  score qualify   color index
a  Anastasia   12.5     yes     Red     a
b       Dima    9.0      no    Blue     b
c  Katherine   16.5     yes  Orange     c
d      James   11.5      no     Red     d
e      Emily    9.0      no   White     e
f    Michael   20.0     yes   White     f
g    Matthew   14.5     yes    Blue     g
h      Laura    NaN      no   Green     h
i      Kevin    8.0      no   Green     i
j      Jonas   19.0     yes     Red     j
k     Suresh   15.5     yes  Yellow     k

In [132]:
df.isna().values.sum()

1

In [135]:
df.drop(['b', 'd'])

name  score qualify   color index
a  Anastasia   12.5     yes     Red     a
c  Katherine   16.5     yes  Orange     c
e      Emily    9.0      no   White     e
f    Michael   20.0     yes   White     f
g    Matthew   14.5     yes    Blue     g
h      Laura    NaN      no   Green     h
i      Kevin    8.0      no   Green     i
j      Jonas   19.0     yes     Red     j
k     Suresh   15.5     yes  Yellow     k

In [137]:
df.reset_index(drop=True)

name  score qualify   color index
0   Anastasia   12.5     yes     Red     a
1        Dima    9.0      no    Blue     b
2   Katherine   16.5     yes  Orange     c
3       James   11.5      no     Red     d
4       Emily    9.0      no   White     e
5     Michael   20.0     yes   White     f
6     Matthew   14.5     yes    Blue     g
7       Laura    NaN      no   Green     h
8       Kevin    8.0      no   Green     i
9       Jonas   19.0     yes     Red     j
10     Suresh   15.5     yes  Yellow     k

In [147]:
a = pd.DataFrame(np.random.random((5, 4)), columns=np.arange(4), index=np.arange(5))
a

0         1         2         3
0  0.886932  0.081239  0.051557  0.150991
1  0.345327  0.530300  0.339849  0.582379
2  0.161637  0.548096  0.699496  0.255761
3  0.528984  0.448038  0.560465  0.378417
4  0.688466  0.449306  0.424769  0.689771

In [149]:
a[0].argmax()

0

In [152]:
a[3].astype(int)

0    0
1    0
2    0
3    0
4    0
Name: 3, dtype: int32

In [155]:
a = pd.DataFrame((1, 2, 3, np.inf, -np.inf, 5))
a[np.isfinite(a)]

0
0  1.0
1  2.0
2  3.0
3  NaN
4  NaN
5  5.0

In [157]:
a.insert(0, 'el primo', np.zeros(6))
a

el primo    0
0       0.0  1.0
1       0.0  2.0
2       0.0  3.0
3       0.0  inf
4       0.0 -inf
5       0.0  5.0

In [159]:
pd.DataFrame([[2, 4], [1, 3]], columns=['col1', 'col2'])

col1  col2
0     2     4
1     1     3

In [160]:
a.columns.get_loc('el primo')

0

In [161]:
a.head(2)

el primo    0
0       0.0  1.0
1       0.0  2.0

In [162]:
a.tail(2)

el primo    0
4       0.0 -inf
5       0.0  5.0

In [163]:
a.nlargest(3, 0)

el primo    0
3       0.0  inf
5       0.0  5.0
2       0.0  3.0

In [164]:
a.nsmallest(3, 0)

el primo    0
4       0.0 -inf
0       0.0  1.0
1       0.0  2.0

In [165]:
a.add_prefix('AAA_')

AAA_el primo  AAA_0
0           0.0    1.0
1           0.0    2.0
2           0.0    3.0
3           0.0    inf
4           0.0   -inf
5           0.0    5.0

In [166]:
a.add_suffix("_BBB")

el primo_BBB  0_BBB
0           0.0    1.0
1           0.0    2.0
2           0.0    3.0
3           0.0    inf
4           0.0   -inf
5           0.0    5.0

In [167]:
a.loc[::-1]

el primo    0
5       0.0  5.0
4       0.0 -inf
3       0.0  inf
2       0.0  3.0
1       0.0  2.0
0       0.0  1.0

In [169]:
a.loc[::, ::-1]

0  el primo
0  1.0       0.0
1  2.0       0.0
2  3.0       0.0
3  inf       0.0
4 -inf       0.0
5  5.0       0.0

In [170]:
a.columns.str.upper()

Index(['EL PRIMO', nan], dtype='object')

In [171]:
a.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   el primo  6 non-null      float64
 1   0         6 non-null      float64
dtypes: float64(2)
memory usage: 224.0 bytes


In [172]:
a.memory_usage()

Index       128
el primo     48
0            48
dtype: int64

In [174]:
a[np.isfinite(a)].interpolate()

el primo         0
0       0.0  1.000000
1       0.0  2.000000
2       0.0  3.000000
3       0.0  3.666667
4       0.0  4.333333
5       0.0  5.000000