In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

In [3]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [4]:
np.add?

In [5]:
np.add??

In [6]:
np.all(np.arange(5))

False

In [7]:
np.any(np.arange(5))

True

In [8]:
np.isfinite(np.array([0, 1, 2, np.inf, np.nan]))

array([ True,  True,  True, False, False])

In [9]:
np.isnan(np.array([0, 1, 2, np.nan]))

array([False, False, False,  True])

In [10]:
np.allclose([1e10,1e-8], [1.00001e10,1e-9])

True

In [11]:
np.greater([1, 2, 5], [2, 3, 5])

array([False, False, False])

In [12]:
np.less([1, 2, 5], [2, 3, 5])

array([ True,  True, False])

In [13]:
np.greater_equal([1, 2, 5], [2, 3, 5])

array([False, False,  True])

In [14]:
np.less_equal([1, 2, 5], [2, 3, 5])

array([ True,  True,  True])

In [15]:
np.array([1, 7, 13, 105]).itemsize

4

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [19]:
np.repeat(5, 10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [20]:
np.arange(30, 71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.random(1)

array([0.23152947])

In [23]:
np.random.randn(15)

array([ 0.78937284,  0.28379649, -1.34280453, -0.97142072,  1.84502851,
       -0.51957085,  0.343645  ,  1.76860726,  0.12386649, -0.24516994,
        0.80884749,  1.05712108, -1.23267458, -0.44817357, -0.35792378])

In [24]:
np.arange(15, 56)[1:-1:]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [25]:
for _ in np.nditer(np.random.random(12).reshape((3,4))):
    print(_)

0.3352227992789648
0.8148291410473525
0.19246076088339892
0.8548182635432171
0.06066796771894134
0.48034956266614526
0.5798635040545246
0.05048019957684513
0.8606351511825506
0.3157825262410905
0.6181508068007443
0.5124825618739758


In [26]:
np.linspace(5, 50, 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [27]:
a = np.arange(21)
a[9:16:] *= -1
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [28]:
np.random.randint(0, 11, 5)

array([4, 7, 0, 1, 6])

In [29]:
a = np.random.randint(0, 11, 5)
b = np.random.randint(0, 11, 5)

a * b

array([10,  0,  9,  2,  0])

In [30]:
np.arange(10, 22).reshape((3, 4))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [31]:
np.arange(10, 22).reshape((3, 4)).shape

(3, 4)

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
a = np.ones(100).reshape((10, 10))
a[1:-1:, 1:-1:] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [35]:
a = np.zeros(16).reshape((4, 4))
a[::2, 1::2] = 1
a[1::2, ::2] = 1
a

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [36]:
np.random.random((3, 3, 3))

array([[[0.35123405, 0.90144592, 0.25466348],
        [0.20892273, 0.78920123, 0.08701986],
        [0.08636632, 0.84967777, 0.28946814]],

       [[0.5352658 , 0.74016572, 0.72689245],
        [0.82862307, 0.86466724, 0.76646617],
        [0.08301393, 0.681914  , 0.86991949]],

       [[0.61999963, 0.71921098, 0.05983806],
        [0.6722672 , 0.37500574, 0.37676599],
        [0.41569908, 0.61760652, 0.13924044]]])

In [37]:
a = np.arange(9).reshape((3,3))
a.sum()
a.sum(axis=0)
a.sum(axis=1)

array([ 3, 12, 21])

In [38]:
a = np.array([4, 5])
b = np.array([7, 10])
a @ b # np.dot(a, b)

78

In [39]:
a = np.arange(0, 9).reshape((3, 3))
b = np.array([1,2,3])
a + b

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [40]:
np.array([1, 2, 3]).tolist()

[1, 2, 3]

In [41]:
np.isnan(np.array([[1, np.nan, 3], [np.nan, 2, 3], [1, 2, np.nan]]))

array([[False,  True, False],
       [ True, False, False],
       [False, False,  True]])

In [42]:
a = np.arange(5)
b = np.arange(5)
a == b

array([ True,  True,  True,  True,  True])

In [43]:
np.arange(1, 151).reshape((-1, 10))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150]])

In [44]:
# np.random.seed(13)
np.random.rand(40)

array([0.4509716 , 0.05972662, 0.49884037, 0.25007787, 0.21316856,
       0.23557226, 0.4786744 , 0.72684996, 0.87474816, 0.5492602 ,
       0.70994335, 0.78717715, 0.5959005 , 0.29206019, 0.98550868,
       0.37044004, 0.06635169, 0.17847976, 0.43658467, 0.03944708,
       0.66789113, 0.13903746, 0.55065409, 0.67369622, 0.2876939 ,
       0.57502839, 0.04197995, 0.27563519, 0.85227575, 0.20533324,
       0.32775131, 0.88949902, 0.45503911, 0.61917602, 0.27355177,
       0.28755828, 0.53684803, 0.06603921, 0.40394326, 0.21322401])

In [45]:
a = np.random.random(16).reshape((4, 4))
a[[0, -1]] = a[[-1, 0]]
a

array([[0.95844545, 0.68746156, 0.24233822, 0.01046529],
       [0.68015226, 0.90695813, 0.04061455, 0.33007349],
       [0.08728616, 0.89872835, 0.43196954, 0.45244758],
       [0.18528837, 0.74016115, 0.82516635, 0.69155002]])

In [46]:
a = np.zeros((5, 6))
a[::2, ::2] = 3
a[1::2, ::2] = 7
a

array([[3., 0., 3., 0., 3., 0.],
       [7., 0., 7., 0., 7., 0.],
       [3., 0., 3., 0., 3., 0.],
       [7., 0., 7., 0., 7., 0.],
       [3., 0., 3., 0., 3., 0.]])

In [47]:
a = np.random.random((4, 4))
np.sort(a)
np.sort(a, axis=0)
np.sort(a, axis=1)

array([[0.35095982, 0.51949698, 0.53086468, 0.97503544],
       [0.19556487, 0.47598282, 0.79495321, 0.98094948],
       [0.03672214, 0.22507673, 0.25023566, 0.79978409],
       [0.20876438, 0.23802601, 0.50022482, 0.7002108 ]])

In [48]:
a = np.random.random((4, 4))
a[a > .6]
a[a < .3]
a[a == 0.25]

array([], dtype=float64)

In [49]:
a = np.random.random((4, 4))
a[a == 0.25] = 1
a[a < 0.4] = 2
a[a > 0.6] = 3

In [50]:
a = np.arange(9).reshape((3, 3))
np.asarray(a)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
a = np.arange(9).reshape((3, 3))
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
a = np.random.random((3, 5, 4))
a

array([[[0.53399398, 0.53303394, 0.07532127, 0.37865022],
        [0.01066149, 0.4503436 , 0.99766018, 0.54836444],
        [0.87463243, 0.84435472, 0.88391716, 0.15757015],
        [0.95611697, 0.23313766, 0.20589884, 0.75822742],
        [0.93282592, 0.64511307, 0.49813462, 0.65093138]],

       [[0.98636489, 0.51308648, 0.71664803, 0.85722441],
        [0.88373972, 0.17753672, 0.04684353, 0.45614962],
        [0.8840757 , 0.50529638, 0.2801107 , 0.55459274],
        [0.11244847, 0.30490143, 0.09469369, 0.20559204],
        [0.64394889, 0.14308043, 0.66877512, 0.3732836 ]],

       [[0.19029935, 0.20600049, 0.92297428, 0.39775152],
        [0.64758868, 0.92168714, 0.57315498, 0.86710276],
        [0.30462156, 0.26228069, 0.27985061, 0.19470425],
        [0.09369115, 0.96075415, 0.93330059, 0.42627137],
        [0.77066888, 0.41364091, 0.72597363, 0.06371274]]])

In [53]:
np.random.random((3, 3)).T

array([[0.49953255, 0.41665536, 0.42382633],
       [0.76954471, 0.89940842, 0.1954885 ],
       [0.44818643, 0.95917642, 0.85848654]])

In [54]:
np.random.random((4, 4))[:, ::-1]

array([[0.57969746, 0.26556847, 0.84684502, 0.03007175],
       [0.53564702, 0.38802738, 0.07817379, 0.16958653],
       [0.22399075, 0.16648867, 0.87636222, 0.65492975],
       [0.93192543, 0.46122138, 0.00639898, 0.43620863]])

In [55]:
a = np.arange(1, 10).reshape((3, 3))
b = np.repeat(10, 9).reshape((3, 3))
a * b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [56]:
a = [1, 2, 3]
np.array(a)

array([1, 2, 3])

In [57]:
np.arange(2, 11).reshape((3, 3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [58]:
a = np.zeros(10)
a[6] = 11
a

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [59]:
np.arange(12, 39)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [60]:
a = np.arange(12, 39)
a[::-1]

array([38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [61]:
a = np.array([1, 2, 3, 4])
a.dtype
a.astype(float)

array([1., 2., 3., 4.])

In [62]:
a = np.ones((3, 3))
a = np.pad(a, pad_width=1)
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
a = np.arange(10, 31, 10)
a = np.append(a, np.arange(40, 91, 10))
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
np.empty((3, 4))

array([[8.29730792e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 2.47098510e-056, 3.92662485e-033,
        4.01719993e-057],
       [3.42357648e-032, 8.82785292e+169, 9.74855359e-072,
        6.44822295e-067]])

In [65]:
np.full((3, 3), 6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [66]:
a = np.array([0, 12, 45.21, 34, 99.91])
a = a * 1.8 + 32 # to fahrenheit
a

array([ 32.   ,  53.6  , 113.378,  93.2  , 211.838])

In [67]:
a = (a - 32) / 1.8 # to celsius
a

array([ 0.  , 12.  , 45.21, 34.  , 99.91])

In [68]:
a = np.arange(9).reshape((3, 3))
a.size
a.itemsize
a.nbytes # a.size * a.itemsize

36

In [69]:
np.unique(np.array([10, 10, 20, 20, 30, 30]))

array([10, 20, 30])

In [70]:
a = np.array([0, 10, 20, 40, 60])
b = np.array([0, 40])
np.in1d(a, b)

array([ True, False, False,  True, False])

In [71]:
a = np.array([0, 10, 20, 40, 60])
b = np.array([10, 30, 40])
np.intersect1d(a, b)

array([10, 40])

In [72]:
a = np.array([0 , 10, 20, 40, 60, 80])
b = np.array([10, 30, 40, 50, 70])
np.setdiff1d(a, b)

array([ 0, 20, 60, 80])

In [73]:
a = np.array([0 , 10, 20, 40, 60, 80])
b = np.array([10, 30, 40, 50, 70])
np.setxor1d(a, b)

array([ 0, 20, 30, 50, 60, 70, 80])

In [74]:
a = np.array([0, 10, 20, 40, 60, 80])
b = np.array([10, 30, 40, 50, 70])
np.union1d(a, b)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [75]:
np.all([1, True])
np.all([1, True, 0])

False

In [76]:
np.any([1, True])
np.any([1, True, 0])

True

In [77]:
np.repeat([1, 2, 3, 4], 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [78]:
np.tile([1, 2, 3, 4], 2)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [79]:
a = np.arange(6)
a.argmax()
a.argmin()

0

In [80]:
a = ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
b = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
np.lexsort((a, b))

array([1, 3, 2, 4, 0], dtype=int64)

In [81]:
np.arange(9).reshape(3, 3).ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
np.logspace(2, 5, 20)

array([   100.        ,    143.84498883,    206.91380811,    297.63514416,
          428.13323987,    615.84821107,    885.86679041,   1274.2749857 ,
         1832.98071083,   2636.65089873,   3792.69019073,   5455.59478117,
         7847.59970351,  11288.37891685,  16237.76739189,  23357.2146909 ,
        33598.18286284,  48329.30238572,  69519.27961776, 100000.        ])

In [83]:
np.tri(4, 3, -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [84]:
np.triu(np.arange(2, 14).reshape((4,3)))

array([[ 2,  3,  4],
       [ 0,  6,  7],
       [ 0,  0, 10],
       [ 0,  0,  0]])

In [85]:
np.tril(np.arange(2, 14).reshape((4,3)), -1)

array([[ 0,  0,  0],
       [ 5,  0,  0],
       [ 8,  9,  0],
       [11, 12, 13]])

In [86]:
np.arange(2, 14).reshape((4,3)).flat[4]

6

In [87]:
np.array([[1, 2, 3]]).swapaxes(0, 1)

array([[1],
       [2],
       [3]])

In [88]:
np.moveaxis(np.ones((3, 4, 2)), 1, 0).shape

(4, 3, 2)

In [89]:
np.rollaxis(np.ones((2, 3, 4, 5)), 3, 1).shape

(2, 5, 3, 4)

In [90]:
np.atleast_1d(12)

array([12])

In [91]:
np.atleast_2d(12)

array([[12]])

In [92]:
np.atleast_3d(12)

array([[[12]]])

In [93]:
np.expand_dims(np.arange(12).reshape(3, 4), axis=1).shape

(3, 1, 4)

In [94]:
np.expand_dims(np.arange(12).reshape(3, 4), axis=1).squeeze().shape

(3, 4)

In [95]:
a = np.array((10,20,30))
b = np.array((40,50,60))
np.column_stack((a, b))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [96]:
np.split(np.arange(1, 15), [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]

In [97]:
np.count_nonzero(np.arange(5))

4

In [98]:
np.zeros((5, 5)) + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [99]:
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [100]:
a = np.zeros(10)
a.flags.writeable = False

In [101]:
np.arange(1e3)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [102]:
np.set_printoptions(precision = 3)
np.random.random(5)

array([0.513, 0.065, 0.337, 0.739, 0.365])

In [103]:
np.delete(np.arange(10), [2, 4, 5])

array([0, 1, 3, 6, 7, 8, 9])

In [104]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])
a[~np.isnan(a).any(axis=1)]

array([[1., 2., 3.]])

In [105]:
a = np.arange(1, 6)
np.linalg.norm(a)

7.416198487095663

In [106]:
a = np.arange(10, 31, 10)
a.sum()

60

In [107]:
a.prod()

6000

In [108]:
# np.savetxt("test.csv", np.zeros(10), delimiter=',')

In [109]:
# np.genfromtxt("test.csv", delimiter=',')

In [110]:
np.percentile(np.arange(1, 6), 50)

3.0

In [111]:
np.where(np.array((1, 0, 0, 1, 1, 1)) == 0)[0]

array([1, 2], dtype=int64)

In [112]:
a = np.random.random((3, 3))
b = np.random.random((3, 3))
np.hstack((a, b))

array([[0.634, 0.24 , 0.557, 0.269, 0.61 , 0.708],
       [0.635, 0.825, 0.012, 0.194, 0.066, 0.178],
       [0.956, 0.692, 0.782, 0.061, 0.087, 0.224]])

In [113]:
np.vstack((a, b))

array([[0.634, 0.24 , 0.557],
       [0.635, 0.825, 0.012],
       [0.956, 0.692, 0.782],
       [0.269, 0.61 , 0.708],
       [0.194, 0.066, 0.178],
       [0.061, 0.087, 0.224]])

In [114]:
np.column_stack((a, b))

array([[0.634, 0.24 , 0.557, 0.269, 0.61 , 0.708],
       [0.635, 0.825, 0.012, 0.194, 0.066, 0.178],
       [0.956, 0.692, 0.782, 0.061, 0.087, 0.224]])

In [115]:
np.row_stack((a, b))

array([[0.634, 0.24 , 0.557],
       [0.635, 0.825, 0.012],
       [0.956, 0.692, 0.782],
       [0.269, 0.61 , 0.708],
       [0.194, 0.066, 0.178],
       [0.061, 0.087, 0.224]])

In [116]:
np.zeros((2, 3, 5, 7)).ndim

4

In [117]:
np.where((np.arange(36).reshape((4, -1)) > 10).any(axis=1))

(array([1, 2, 3], dtype=int64),)

In [118]:
np.fromiter((n for n in range(15)), dtype=float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [119]:
a = np.random.random(12).reshape((3, 4))
b = np.random.random(12).reshape((4, 3))
a @ b

array([[0.948, 0.936, 0.447],
       [1.174, 1.158, 0.943],
       [1.5  , 1.602, 0.962]])

In [120]:
a = np.random.random(5)
b = np.random.random(5)
np.outer(a, b)

array([[0.253, 0.565, 0.626, 0.063, 0.669],
       [0.143, 0.32 , 0.354, 0.035, 0.379],
       [0.175, 0.391, 0.434, 0.043, 0.464],
       [0.205, 0.459, 0.508, 0.051, 0.543],
       [0.147, 0.329, 0.364, 0.036, 0.39 ]])

In [121]:
np.inner(a, b)

1.446536874320761

In [122]:
a = np.random.random((2, 2))
b = np.random.random((2, 2))
np.cross(a, b)

array([0.521, 0.006])

In [123]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

In [124]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [125]:
a = np.array([[10, 40], [30, 20]])
np.sort(a)

array([[10, 40],
       [20, 30]])

In [126]:
np.sort(a, axis = 0)

array([[10, 20],
       [30, 40]])

In [127]:
np.sort(a, axis = 1)

array([[10, 40],
       [20, 30]])

In [128]:
np.sort(a, axis = None)

array([10, 20, 30, 40])